### PR TITLE
Expr in fixes

### PR DESCRIPTION
**Pull request by marcmengel**
Assorted expression evaluation tests and a few fixes.

### CODE REVIEW

**Review by alisonpeisker — APPROVED** [review]
It looks good to me. Just one question - there are some tests that have the same name, like there are two test_exp_13's and test_exp_23's - was this intentional?

**Comment by marcmengel** [comment]
Ack!  no!  That was not intentional... Thanks for noticing that.  Update pushed.

**Comment by alisonpeisker** [comment]
Thanks, I also just noticed there are two 5's and 6's...

**Comment by marcmengel** [comment]
Okay, got serious.  Ran:
 cat test*.py | grep 'def ' | sort | uniq -c
and found another test ( test_metacat_query_q ) that had a duplicated name... 
This time I think we really have them all. :-)

**Comment by alisonpeisker** [comment]
I thought I had deleted one of the copies of test_metacat_query_q in my last pull request because it seems that it wasn't just the name that was duplicated but the whole test.

**Pull request merged**
